### ISSUE TITLE
Adding Finnish RTE test ledger

### ISSUE THREAD

**Issue by jgmikael** [L3-iGrant/datawallet-metadata#9]
Hi, Lal proposed that one could add support for specific ledgers by sending the genesis, does it work like this (see attached file) 
[genesis-transactions.zip](https://github.com/L3-iGrant/datawallet-metadata/files/10457073/genesis-transactions.zip)

**Comment by lalc** [comment]
You could go and directly edit the file in a separate branch https://github.com/L3-iGrant/datawallet-metadata/blob/main/ledgers.json

Once added, you can raise a PR to merge to master and go live.

**Comment by lalc** [comment]
@lainean has added this and raised the PR, so perhaps we could close this PR?
